### PR TITLE
Remove quotes around values of type and boundary parameters in accept header field 

### PR DESCRIPTION
**Pull request by hackermd**
See conversation on JavaScript client: https://github.com/dcmjs-org/dicomweb-client/issues/57

### CODE REVIEW

**Comment by sedghi** [comment]
Oh I just saw this, great!
@hackermd @adamvonpaternos We need this for the OHIF new release, Is there any help I can provide to get this done?

**Comment by sedghi** [comment]
we decided to go with a quote = true by default to not break servers requiring it, and added that config to all of our app configurations to be false.

**Comment by hackermd** [comment]
@sedghi I think you are referring to the JavaScript implementation. This is the Python implementation.

I understand that the preflight requests by the browser pose a performance bottleneck for web-based viewers, but that should not affect Python programs. Since the changes of this PR would make the client non-conformant with HTTP, we have decided against merging the PR and for keeping the behavior as is.

**Comment by sedghi** [comment]
@hackermd oops you are right, I thought this is the JS implementation

**Comment by sedghi** [comment]
I added the PR here https://github.com/dcmjs-org/dicomweb-client/pull/62

**Pull request closed without merging**
